version: '3.8'
services:
  tic_tac_toe:
    container_name: tictactoe
    image: tic_tac_toe:PA
    build:
      context: ./
      target: production
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: admin
      DB_NAME: postgres
      JWT_SECRET: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYmhvc3QiOiJsb2NhbGhvc3QiLCJkYl9uYW1lIjoiY29uc2VnbmEiLCJkYl91c2VyIjoicG9zdGdyZXMifQ.k4lTFKTcNRIJBQNfEqFs6AeAxlFW1gpd1KjQfF8PtmM
    links:
      - db
    volumes:
      - './:/src'
  db:
    image: postgres:14.1-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    volumes: 
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
volumes:
  db:
    driver: local



